In [1]:
import numpy as np

## unit conversions

In [2]:
### Kh2018:
# verify that units are kg N /s not kg NO3/s: 
# if you use molecular mass for N, you get back a reasonable mean nitrate concentration:
# 64 kg/s / (143*10^3 m3/s) * (1000 g/kg) / (62.0049 g/mol)*(10*3mmol/mol) = kg/s*s/m3*g/kg*mol/g*mmol/mol=mmol/m3 = ug/L
64/143/62.0049*10**3, 64/143/14.0067*10**3

(7.2180174075346875, 31.952740299460082)

In [3]:
# now convert SJDF flux of 61 kg/s to kmol/s:
# 61 kg/s  * (1000 g/kg) / (14.0067 g N/mol) *(1e-3 kmol/mol) = kmol/s
61/14.0067

4.355058650502974

In [4]:
# now convert SJDF flux of 61 kg/s to Gmol/yr:
# kmol/s * 1e-6 Gmol/kmol *3600 s/hr * 24 hr/day *365.25 d/yr = Gmol/yr
61/14.0067*1e-6*3600*24*365.25

137.43519886911264

In [5]:
# additional 3 kg/s from north (kmol/s):
3/14.0067 

0.21418321231981838

In [6]:
# additional 3 kg/s from north (Gmol/yr):
3/14.0067 *1e-6*3600*24*365.25

6.7591081411039

In [7]:
### unit conversion:
#Mackas and Harrison: 2600-2900 tonnes N/day JDFS deep estuarine circulation nitrate
# 1 tonne = 1e3 kg
#14.0067 g/mol N
2600*1e3/(24*3600)*1e3/14.0067,2900*1e3/(24*3600)*1e3/14.0067 # mol/s

(2148.4427161710173, 2396.339952652289)

In [8]:
### unit conversion: to Gmol/yr
#Mackas and Harrison: 2600-2900 tonnes N/day JDFS deep estuarine circulation nitrate
# 1 tonne = 1e3 kg
#14.0067 g/mol N
# tonnes N/day * 1e3 kg/tonne * 1/14.0067 kmol/kgN * 1e-6 Gmol/kmol * 365.25 days/yr
2600*1e3/14.0067*1e-6*365.25,2900*1e3/14.0067*1e-6*365.25

(67.79969585983851, 75.62273768981986)

In [9]:
#net:
400*1e3/(24*3600)

4.62962962962963

In [10]:
# Sutton surface DIN export Mmol/yr to kmol/s
np.array((8800,39800))*1e3/(24*3600*365.25)

array([0.27885517, 1.26118589])

In [11]:
# Sutton total DIN/particulate to sediment:
np.array((1450,490))*1e3/(24*3600*365.25)

array([0.04594773, 0.01552716])

In [12]:
600*1e3/(24*3600)

6.944444444444445

In [13]:
## Sutton marine PN to buried sediment, South and North, upper bound:
np.array((3515,676))*1e3/(24*3600*365.25)

array([0.11138363, 0.02142115])

In [ ]:
## Sutton marine PN to buried sediment, South and North, upper bound, to nmol/m2/s
np.array((3515,676))*1e3/(24*3600*365.25)*1e12/(7735*1e6)

In [14]:
## Sutton remineralization:
22000*1e3/(24*3600*365.25)

0.6971379319086369

In [15]:
## Sutton PP: 23400 +/-1700 Mmol/yr from figure and text
np.array((23400,1700))*1e3/(24*3600*365.25)

array([0.74150125, 0.05386975])

In [16]:
## Sutton PP: 23400 +/-1700 Mmol/yr from figure and text: convert to nmol N/m2/s
# Mmol/yr* 1e12 umol/Mmol* 1/(24*3600*365.25 yr/s)/(7735*1e6 m^2)
np.array((23400,1700))*1e12/(24*3600*365.25)/(7735*1e6)*1e3

array([95.8631228,  6.9644149])

In [17]:
# model kmol/s to nmol/m2/s:
np.array((1.57, 1.49, 1.39))*1e12/(9815*1e6)

array([159.95924605, 151.80845644, 141.61996943])

In [18]:
# model PP kmol/s to nmol/m2/s:
np.array((1.57, 1.49, 1.39))*1e12/(9815*1e6)

array([159.95924605, 151.80845644, 141.61996943])

In [19]:
## Sutton PP: 260-300 gC/m2/yr from text to kmol/s
np.array((260,300))*1/12.0107/6.6*7735*1e6*1e-3/(24*3600*365.25)

array([0.80392853, 0.92760985])

##### sutton PP range to nmol

In [20]:
## Sutton PP: 260-300 gC/m2/yr from text to nmol/m2/s:
# 
np.array((260,300))*1/12.0107/6.6*1e9/(24*3600*365.25)

array([103.93387653, 119.92370369])

In [21]:
## try to reproduce Sutton's conversion:
# 280 gC/m2/yr * 1molC/12.0107 gC * 1mol N/ 6.6mol C * 7735*1e6 m2 * 1e-6 Mmol/mol -> Mmol/yr
# ~=23 400 Mmol yr 1
280/12.0107/6.6*7735

27321.597837887482

In [22]:
## reversing this,
# 23400 Mmol/yr converts to:
23400/7735*6.6*12.0107 # 240 gC/m2/yr

239.8102789915966

In [23]:
## Mackas PP: actually Harrison PP 300 gC/m2/yr from text to nmolN /m2/s:
300/12.011/6.6*1e9/(24*3600*365.25)

119.9207083432193

In [24]:
## Mackas PP: actually Harrison PP 300 gC/m2/yr from text to nmolN /m2/s:
280/12.011/6.6*1e9/(24*3600*365.25)

111.92599445367135

In [25]:
#Mackas N buiral: 100 tonnes N/day, 6800 km2; 1tonne=1e3kg
#100 tonnes N/day* 1e6g/tonne * 1mol/14.0067gN * 1day/(24*3600 s) * 1e9/(6800*1e6 m2) nmol/mol-> nmol/m2/s
100*1e6/14.0067/(24*3600)*1e9/(6800*1e6)

12.151825317709376

In [26]:
#400 gC/m2/yr to nmol N/m2/s:
# 400 gC/m2/yr * 1/12.011 molC/gC *1e9 nmol/mol *(1/(24*3600*365.25) yr/s)
400/12.011/6.6*1e9/(24*3600*365.25)

159.89427779095908

In [27]:
#511 (Stockner maximum at 1 station)gC/m2/yr to nmol N/m2/s:
# 511 gC/m2/yr * 1/12.011 molC/gC *1e9 nmol/mol *(1/(24*3600*365.25) yr/s)
511/12.011/6.6*1e9/(24*3600*365.25)

204.2649398779502

In [28]:
#280 gC/m2/yr to nmol/m2/s:
280* 1/12.011* 

SyntaxError: invalid syntax (<ipython-input-28-e92f85ea196d>, line 2)

In [ ]:
# PON flux: 0.2 kmolN/s model 9815 area
0.2*1e12/(9815*1e6)

In [ ]:
# PON flux:  0.11 kmolN/s Sutton 7735 area
0.11*1e12/(7735*1e6)

In [ ]:
# Harrison gC/m2/d to mmolN/m2/d:
# gC/m2/d * (1/12.011 molC/gC) * (1mol N/ 6.6mol C) * (1e3 mmol/mol)-> mmolN/m2/d
np.array((1.2,0.2))/12.001/6.6*1e3

In [ ]:
 The calculated PNMar implies a total pro- duction of 23400 Mmol yr 1 PNMar for the entire strait as- suming a surface area of 7735 km2 . 

In [ ]:
#Sutton PP:
# 23400+/11700 Mmol N/yr * 1e6 mol/Mmol *6.6 molC/molN* 12.01 g/molC /(7735*1e6 m2)= ?? gC/m2/yr
np.array((23400,1700))*1e6*6.6* 12.01/(7735*1e6)

In [ ]:
# assume they actually used 6800 km2:
# 23400 Mmol N/yr * 1e6 mol/Mmol *6.6 molC/molN* 12.01 g/molC /(7735*1e6 m2)= ?? gC/m2/yr
23400*1e6*6.6* 12.01/(6800*1e6)

In [ ]:
# Sutton annual influx of din by advection from pacific to SalishSea: 85300+/-55700 Mmol/yr
# and 69500+/-44200 Mmol/yr out
# kmol/s:

In [ ]:
85300/(365.25*24*3600)*1e3,55700/(365.25*24*3600)*1e3

In [ ]:
# Sutton annual influx of din by advection from pacific to SoG: 29900+/-19500 Mmol/yr
# and 24300+/-15500 Mmol/yr out

In [ ]:
# Mmol/yr *(1 yr /365 days)*(1 day / 24*3600 s) *1e6 = mol/s
29900/(365.25*24*3600)*1e6,19500/(365.25*24*3600)*1e6

In [ ]:
# Mmol/yr*1e6 mol/Mmol*62.0049 g/mol * 1yr/(365.25*24*3600 s)*1kg/(1e3g)=kg/s
29900*1e6*62.0049/(365.25*24*3600)*1e-3

In [ ]:
# Mmol/yr*1e6 mol/Mmol*62.0049 g/mol * 1yr/(365.25*24*3600 s)*1kg/(1e3g)=kg/s
24300*1e6*62.0049/(365.25*24*3600)*1e-3

In [ ]:
58.7480198113925-47.745046201232036

In [ ]:
15500*1e6*62.0049/(365.25*24*3600)*1e-3

In [ ]:
19500*1e6*62.0049/(365.25*24*3600)*1e-3